spring:
  profiles:
    active:
      -   dog
      -   EN
      -   dev
barath :
      username: YmlUserName
      password: YmlPassword
      jdbcurl: YmlUrl
---
spring:
    profiles: prod
barath:
    username: YmlProdUserName
    password: YmlProdPassword
    jdbcurl: YmlProdUrl
